# Generated by Django 6.0.3 on 2026-04-05 16:33

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accelerator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("max_energy_gev", models.DecimalField(decimal_places=3, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("commissioned_date", models.DateField()),
                ("webhook_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CollisionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField()),
                ("energy_gev", models.DecimalField(decimal_places=3, max_digits=12)),
                ("luminosity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("particle_count", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                ("atomic_number", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("atomic_mass", models.DecimalField(decimal_places=6, max_digits=12)),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["atomic_number"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_image", models.ImageField(upload_to="event_images/originals/")),
                ("thumbnail", models.ImageField(blank=True, upload_to="event_images/thumbnails/")),
                ("processed_image", models.ImageField(blank=True, upload_to="event_images/processed/")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collision_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lab.collisionevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("avg_energy_gev", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accelerator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to="lab.accelerator",
                    ),
                ),
                (
                    "lead_researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collisionevent",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collision_events",
                to="lab.experiment",
            ),
        ),
        migrations.CreateModel(
            name="ExperimentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="lab.experimentcategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "experiment categories",
            },
        ),
        migrations.AddField(
            model_name="experiment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.experimentcategory",
            ),
        ),
        migrations.CreateModel(
            name="ExperimentStatusEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="status_events",
                        to="lab.experiment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="experiment",
            trigger=pgtrigger.compiler.Trigger(
                name="experiment_insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "lab_experimentstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'experiment.insert\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="659eb56df812f1d6de25a5a857d9f60305bbf81a",
                    operation="INSERT",
                    pgid="pgtrigger_experiment_insert_insert_e12ab",
                    table="lab_experiment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="experiment",
            trigger=pgtrigger.compiler.Trigger(
                name="experiment_status_change_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func='INSERT INTO "lab_experimentstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'experiment.status_change\', NEW."id", NEW."status"); RETURN NULL;',
                    hash="147901d972c090d0c9a4958954b109abbc4a5021",
                    operation="UPDATE",
                    pgid="pgtrigger_experiment_status_change_update_5f580",
                    table="lab_experiment",
                    when="AFTER",
                ),
            ),
        ),
    ]
